apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/nikhilp047/gitops-infra.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-rollout

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      #selfHeal: true