apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp-rollouts
spec:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause: {duration: 10}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}
  revisionHistoryLimit: 2 
  selector:
    matchLabels:
      app: myapp-rollout
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp-rollout
    spec:
      containers:
      - name: myapp-rollout
        image: nikhilp047/todoapp:f20fba6e51aceebf160a1b55d9ac6db2628b78d5
        ports:
        - containerPort: 8080 #test
